version: '3'
services:
  duplex-cloud-scan:
    image: duplex-cloud-scan
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - GOOGLE_CLOUD_PROJECT=api-project-175925620434
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service_account.json
